//
//  RCDLiveMessageCellNotificationModel.m
//  RongIMKit
//
//  Created by xugang on 15/1/29.
//  Copyright (c) 2015年 RongCloud. All rights reserved.
//

#import "RCDLiveMessageCellNotificationModel.h"

NSString *const RCDLiveCONVERSATION_CELL_STATUS_SEND_BEGIN = @"RCDLiveCONVERSATION_CELL_STATUS_SEND_BEGIN";
NSString *const RCDLiveCONVERSATION_CELL_STATUS_SEND_FAILED = @"RCDLiveCONVERSATION_CELL_STATUS_SEND_FAILED";
NSString *const RCDLiveCONVERSATION_CELL_STATUS_SEND_SUCCESS = @"RCDLiveCONVERSATION_CELL_STATUS_SEND_SUCCESS";
NSString *const RCDLiveCONVERSATION_CELL_STATUS_SEND_PROGRESS = @"RCDLiveCONVERSATION_CELL_STATUS_SEND_PROGRESS";
NSString *const RCDLiveCONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE = @"RCDLiveCONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE";
NSString *const RCDLiveCONVERSATION_CELL_STATUS_SEND_HASREAD = @"RCDLiveCONVERSATION_CELL_STATUS_SEND_HASREAD";//对方已读状态

@implementation RCDLiveMessageCellNotificationModel

@end
