//
//  RCMessageCellNotificationModel.m
//  RongIMKit
//
//  Created by xugang on 15/1/29.
//  Copyright (c) 2015年 RongCloud. All rights reserved.
//

#import "RCMessageCellNotificationModel.h"

NSString *const CONVERSATION_CELL_STATUS_SEND_BEGIN = @"CONVERSATION_CELL_STATUS_SEND_BEGIN";
NSString *const CONVERSATION_CELL_STATUS_SEND_FAILED = @"CONVERSATION_CELL_STATUS_SEND_FAILED";
NSString *const CONVERSATION_CELL_STATUS_SEND_SUCCESS = @"CONVERSATION_CELL_STATUS_SEND_SUCCESS";
NSString *const CONVERSATION_CELL_STATUS_SEND_PROGRESS = @"CONVERSATION_CELL_STATUS_SEND_PROGRESS";
NSString *const CONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE = @"CONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE";
NSString *const CONVERSATION_CELL_STATUS_SEND_HASREAD = @"CONVERSATION_CELL_STATUS_SEND_HASREAD";//对方已读状态

@implementation RCMessageCellNotificationModel

@end
